addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.4.6")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"      % "2.2.1")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype" % "3.9.21")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"   % "5.10.0")
