addSbtPlugin("pl.project13.scala" % "sbt-jmh"      % "0.4.6")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt" % "2.5.2")
addSbtPlugin("com.github.sbt"     % "sbt-pgp"      % "2.3.1")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype" % "3.12.2")
addSbtPlugin("com.github.sbt"     % "sbt-header"   % "5.11.0")
